import { Router, type IRouter } from "express";
import {
  Document,
  Paragraph,
  TextRun,
  HeadingLevel,
  Packer,
  AlignmentType,
  UnderlineType,
} from "docx";
import {
  formatCitation,
  exportBibtex,
  type CitationMetadata,
  type CitationStyle,
  ALL_STYLES,
} from "../lib/citations";

const router: IRouter = Router();

// ─── Types ────────────────────────────────────────────────────────────────────

interface IncomingItem {
  title?: string;
  authors?: string[];
  year?: number | null;
  journal?: string | null;
  doi?: string | null;
  url?: string | null;
}

type ExportFormat = "txt" | "bib" | "docx";

const VALID_STYLES = new Set<string>(ALL_STYLES);

function pickStyle(raw: unknown): CitationStyle {
  const s = typeof raw === "string" ? raw.toLowerCase() : "";
  return VALID_STYLES.has(s) ? (s as CitationStyle) : "apa";
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function itemToMeta(item: IncomingItem): CitationMetadata {
  return {
    title: item.title ?? "Untitled",
    authors: item.authors ?? [],
    year: item.year != null ? String(item.year) : undefined,
    journal: item.journal ?? undefined,
    doi: item.doi ?? undefined,
    url: item.url ?? undefined,
  };
}

/** First author surname for alphabetical sorting. */
function firstSurname(authors: string[] = []): string {
  const first = authors[0] ?? "";
  const commaIdx = first.indexOf(",");
  if (commaIdx !== -1) return first.slice(0, commaIdx).trim().toLowerCase();
  const words = first.trim().split(/\s+/);
  return (words[words.length - 1] ?? "").toLowerCase();
}

/** Format a human-readable style label for document headings. */
function styleLabel(style: CitationStyle): string {
  const map: Record<CitationStyle, string> = {
    apa: "APA 7th",
    vancouver: "Vancouver",
    harvard: "Harvard",
    mla: "MLA 9th",
    chicago: "Chicago 17th",
  };
  return map[style] ?? style.toUpperCase();
}

// ─── POST /api/export/bibliography ───────────────────────────────────────────

router.post("/export/bibliography", async (req, res): Promise<void> => {
  const body = req.body as {
    items?: IncomingItem[];
    style?: string;
    format?: string;
    universityName?: string;
  };

  // --- validate ---
  if (!Array.isArray(body.items) || body.items.length === 0) {
    res.status(400).json({ error: "items must be a non-empty array" });
    return;
  }
  const format = (body.format ?? "txt") as ExportFormat;
  if (!["txt", "bib", "docx"].includes(format)) {
    res.status(400).json({ error: "format must be txt, bib, or docx" });
    return;
  }

  const style = pickStyle(body.style);
  const universityName = typeof body.universityName === "string"
    ? body.universityName.trim()
    : "";

  // Convert items → CitationMetadata, sorted A–Z by first author surname
  const metas: CitationMetadata[] = body.items
    .map(itemToMeta)
    .sort((a, b) => firstSurname(a.authors).localeCompare(firstSurname(b.authors)));

  // ── Plain text ──────────────────────────────────────────────────────────────
  if (format === "txt") {
    const lines = metas.map((m) => formatCitation(m, style));
    res.type("text/plain").send(lines.join("\n\n"));
    return;
  }

  // ── BibTeX ──────────────────────────────────────────────────────────────────
  if (format === "bib") {
    const bibtex = exportBibtex(metas);
    res.type("text/plain").send(bibtex);
    return;
  }

  // ── Word (.docx) ─────────────────────────────────────────────────────────────
  const today = new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  const titleText = universityName
    ? `Bibliography — ${universityName}`
    : "Bibliography";

  const subtitleText = `Generated by ScholarForge · ${styleLabel(style)} format · ${today}`;

  const citations = metas.map((m) => formatCitation(m, style));

  const citationParagraphs = citations.map((c, i) =>
    new Paragraph({
      children: [
        new TextRun({
          text: `${i + 1}.\u2003`,
          size: 24,
          color: "555555",
        }),
        new TextRun({
          text: c,
          size: 24,
        }),
      ],
      spacing: {
        after: 120, // 6pt after each citation (1pt = 20 twips)
        line: 276,  // ~1.15 line spacing
      },
      indent: {
        left: 360,      // 0.25 in
        hanging: 360,   // hanging indent to align body text
      },
    })
  );

  const doc = new Document({
    creator: "ScholarForge",
    title: titleText,
    description: subtitleText,
    styles: {
      default: {
        document: {
          run: {
            font: "Calibri",
            size: 24,
            color: "222222",
          },
          paragraph: {
            spacing: { after: 80 },
          },
        },
      },
    },
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: 1440,    // 1 inch
              right: 1440,
              bottom: 1440,
              left: 1440,
            },
          },
        },
        children: [
          // Title
          new Paragraph({
            children: [
              new TextRun({
                text: titleText,
                bold: true,
                size: 40, // 20pt
                color: "1a3a2a",
                font: "Calibri",
              }),
            ],
            spacing: { after: 120 },
          }),
          // Subtitle
          new Paragraph({
            children: [
              new TextRun({
                text: subtitleText,
                size: 18, // 9pt
                color: "888888",
                italics: true,
                font: "Calibri",
              }),
            ],
            spacing: { after: 400 },
          }),
          // Divider paragraph
          new Paragraph({
            children: [
              new TextRun({
                text: "─".repeat(60),
                color: "dddddd",
                size: 16,
              }),
            ],
            spacing: { after: 320 },
          }),
          // Citation entries
          ...citationParagraphs,
          // Footer note
          new Paragraph({
            children: [
              new TextRun({
                text: `\n${citations.length} reference${citations.length !== 1 ? "s" : ""} · ScholarForge`,
                size: 16,
                color: "aaaaaa",
                italics: true,
              }),
            ],
            spacing: { before: 480 },
          }),
        ],
      },
    ],
  });

  try {
    const buffer = await Packer.toBuffer(doc);
    const base64 = buffer.toString("base64");
    res.json({ base64, format: "docx", count: citations.length });
  } catch (err) {
    const msg = err instanceof Error ? err.message : "docx generation failed";
    res.status(500).json({ error: msg });
  }
});

export default router;
