import { Router, type IRouter } from "express";
import healthRouter from "./health";
import supervisorsRouter from "./supervisors";
import searchRouter from "./search";
import workspaceRouter from "./workspace";
import paraphraseRouter from "./paraphrase";
import similarityRouter from "./similarity";
import citeRouter from "./cite";
import exportRouter from "./export";
import gapsRouter from "./gaps";
import litreviewRouter from "./litreview";
import argmapRouter from "./argmap";
import coachRouter from "./coach";
import visualsRouter from "./visuals";
import plagiarismRouter from "./plagiarism";
import questionRouter from "./question";
import papergraphRouter from "./papergraph";
import citecontextRouter from "./citecontext";
import outlineRouter from "./outline";
import journalsRouter from "./journals";
import digestRouter from "./digest";
import methodologyRouter from "./methodology";
import scheduleRouter from "./schedule";
import posterRouter from "./poster";
import abstractRouter from "./abstract";
import pdfchatRouter from "./pdfchat";
import conceptRouter from "./concept";
import languageRouter from "./language";

const router: IRouter = Router();

router.use(healthRouter);
router.use(supervisorsRouter);
router.use(searchRouter);
router.use(workspaceRouter);
router.use(paraphraseRouter);
router.use(similarityRouter);
router.use(citeRouter);
router.use(exportRouter);
router.use(gapsRouter);
router.use(litreviewRouter);
router.use(argmapRouter);
router.use(coachRouter);
router.use(visualsRouter);
router.use(plagiarismRouter);
router.use(questionRouter);
router.use(papergraphRouter);
router.use(citecontextRouter);
router.use(outlineRouter);
router.use(journalsRouter);
router.use(digestRouter);
router.use(methodologyRouter);
router.use(scheduleRouter);
router.use(posterRouter);
router.use(abstractRouter);
router.use(pdfchatRouter);
router.use(conceptRouter);
router.use(languageRouter);

export default router;
